import = [
    "~/.config/alacritty/themes/themes/afterglow.toml"
]

[window]
opacity = 0.97

[colors.primary]
background = "#0e0b00"
#background = "#181616"

#[colors.cursor]
#text = "#0e0b00"
#cursor = "#ffffff"

[font.normal]
family = "Fira Mono Nerd Font"

[font]
size = 16.5
