import = [
    "~/.config/alacritty/themes/themes/kanagawa_dragon.toml"
]

[window]
opacity = 0.97

[font.normal]
family = "Fira Mono Nerd Font"

[colors.primary]
background = "#0e0b00"

[font]
size = 16
