import = [
    "~/.config/alacritty/themes/themes/afterglow.toml"
]

[env]
term = "xterm-256color"

[window]
opacity = 0.9

[colors.primary]
background = "#0d0b00"
#background = "#181616"

#[colors.cursor]
#text = "#0e0b00"
#cursor = "#ffffff"

[font.normal]
family = "0xProtoNerdFontPropo"

[font]
size = 16
