import = [
    "~/.config/alacritty/themes/themes/ubuntu.toml"
]

[window]
opacity = 0.94

[colors.primary]
background = "#0e0b00"
#background = "#181616"

[colors.cursor]
text = "#0e0b00"
cursor = "#ffffff"

[font.normal]
family = "Fira Mono Nerd Font"

[font]
size = 17
